name: Preparing react_app to deploy on server
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # path-ignore:
  #   - './github/workflow/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: receive repository code
        uses: actions/checkout@v4
      - name: Install project dependencies
        run: npm ci
      - name: Test application
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: receive repository code
        uses: actions/checkout@v4
      - name: Install project dependencies
        run: npm ci
      - name: lint app
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: receive repository code
        uses: actions/checkout@v4
      - name: Install project dependencies
        run: npm ci
      - name: Building project (React)
        run: npm run build
